[versions]
activity-compose = "1.8.2"
androidx-core-ktx = "1.16.0"
androidx-lifecycle-runtime-ktx = "2.9.1"
androidx-activity-compose = "1.10.1"
androidx-compose-bom = "2025.06.01"
androidx-ui = "1.8.3"
androidx-material3 = "1.3.2"
androidx-hilt-compose-navigation = "1.2.0"
coil-compose = "2.5.0"
coil-compose-version = "2.6.0"
core-ktx = "1.12.0"
gradle = "2.3.2"
hilt = "2.51.1"
kotlinx-coroutines-android = "1.9.0"
ksp = "1.9.21-1.0.15"
kotlinx-coroutines = "1.7.3"
lifecycle-runtime-compose = "2.9.1"
lifecycle-runtime-compose-version = "2.7.0"
lifecycle-runtime-ktx = "2.7.0"
material3 = "1.1.2"
navigation-compose = "2.7.6"
retrofit = "2.11.0"
converter-gson = "2.11.0"
converter-scalars = "2.11.0"
logging-interceptor = "4.12.0"
junit = "4.13.2"
androidx-junit = "1.2.1"
androidx-espresso-core = "3.6.1"
androidx-navigation-compose = "2.9.0"
accompanist-permissions = "0.32.0"
agp = "8.9.1"
appcompat = "1.7.1"
material = "1.12.0"
ui = "1.5.8"
ui-test-manifest = "1.5.8"
ui-tooling = "1.5.8"
ui-tooling-preview = "1.5.8"

[plugins]
android-application = { id = "com.android.application", version = "8.9.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.10" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-library = { id = "com.android.library", version.ref = "agp" }

[libraries]
androidx-activity-compose-v182 = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
androidx-lifecycle-runtime-compose-v270 = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose-version" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-lifecycle-runtime-ktx-v270 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-compose-version" }
androidx-material3-v112 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose-v276 = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "androidx-ui" }
androidx-ui-test-manifest-v158 = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui-test-manifest" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-ui" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-material3" }
androidx-hilt-compose-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-compose-navigation" }
androidx-ui-tooling-preview-v158 = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui-tooling-preview" }
androidx-ui-tooling-v158 = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui-tooling" }
androidx-ui-v158 = { module = "androidx.compose.ui:ui", version.ref = "ui" }
coil-compose-v240 = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
coil-compose-v260 = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose-version" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
kotlinx-coroutines-android-v190 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter-gson" }
converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "converter-scalars" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-ui" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-ui" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-ui" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-permissions" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
